[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
pump_fun = "CecW3x9Ztd5fAi4azx44ESz8Z9xjWqi5suv1LYHyKoao"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
